# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build app
      run: |
        cd app
        yarn
        yarn build
    - name: Pack app
      run: |
        mkdir app
        mv ./app/dist/index.html app
        mv ./app/dist app
    - name: Upload app
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: app

  deploy:

    runs-on: ubuntu-latest

    needs: build

    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
    - name: Clear assets
      run: |
        [ ! -e dist ] || rm -rf dist
    - name: Download app
      uses: actions/download-artifact@v1
      with:
        name: app
    - name: push
      shell: bash
      run: |
          git config --global user.email "argon.argon.argon+github.topics.trending.deploy@gmail.com"
          git config --global user.name "github-topics-trending-deploy"
          git add .
          git commit -m 'Deploy app'
          git push origin gh-pages
