# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  repository_dispatch:
    types: [test_trigger]
  schedule:
    - cron: "0 3 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build batch script
      run: |
        cd batch
        yarn
        yarn build
    - name: Upload batch script
      uses: actions/upload-artifact@v1
      with:
        name: batch
        path: batch/dist/index.js

  crawl:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [c, js]
        date: [daily, weekly, monthly]

    needs: build

    steps:
    - name: Download batch script
      uses: actions/download-artifact@v1
      with:
        name: batch
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date "+%Y%m%d")"
    - name: Crawling
      shell: bash
      run: |
        node batch/index.js --language ${{ matrix.language }} --date-range ${{ matrix.date }} >> ${{ steps.date.outputs.date}}_${{ matrix.language}}_${{ matrix.date }}.json
    - name: Upload result
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.date.outputs.date}}_${{ matrix.language}}_${{ matrix.date }}.json
        path: ${{ steps.date.outputs.date}}_${{ matrix.language}}_${{ matrix.date }}.json
