# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  repository_dispatch:
    types: [test_trigger]
  schedule:
    - cron: "0 3 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build batch script
      run: |
        cd batch
        yarn
        yarn build
    - name: Upload batch script
      uses: actions/upload-artifact@v1
      with:
        name: batch
        path: batch/dist/index.js

  crawl:

    runs-on: ubuntu-latest

    needs: build

    env:
      LANGUAGES: "c cpp js python ts csharp java elm"
      DATE_RANGES: "daily weekly monthly"
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    steps:
    - name: Download batch script
      uses: actions/download-artifact@v1
      with:
        name: batch
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date "+%Y%m%d")"
    - name: Crawling
      shell: bash
      run: |
        for LANG in $LANGUAGES;
        do
            for DATE_RANGE in $DATE_RANGES;
            do
                mkdir -p assets/topics/${{ steps.date.outputs.date}}/${LANG}
                node batch/index.js --language ${LANG} --date-range ${DATE_RANGE} >> assets/topics/${{ steps.date.outputs.date}}/${LANG}/${DATE_RANGE}.json
                sleep 5
            done
        done
    - name: Upload result
      uses: actions/upload-artifact@v1
      with:
        name: assets
        path: assets

  push:
    runs-on: ubuntu-latest

    needs: crawl

    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Download crawling results
      uses: actions/download-artifact@v1
      with:
        name: assets
    - name: push
      shell: bash
      run: |
          python ./tools/gen_index.py ./assets/topics > ./assets/topics/index.json
          git config --global user.email "argon.argon.argon+github.topics.trending.crawler@gmail.com"
          git config --global user.name "github-topics-trending-crawler"
          git add .
          git commit -m 'Add topics'
          git push origin gh-pages
